[changelog]
# changelog header
header = """
# Welcome to the changelog 🚀 \n
All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased] 🌋
{% endif %}\
{% if previous %}\
    {% if previous.commit_id %}
        [{{ previous.commit_id | truncate(length=7, end="") }}]({{ previous.commit_id }})...\
            [{{ commit_id | truncate(length=7, end="") }}]({{ commit_id }})
    {% endif %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }}))\
          {% for footer in commit.footers -%}
            , {{ footer.token }}{{ footer.separator }}{{ footer.value }}\
          {% endfor %}\
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- grupo platino dev team -->
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
	{ message = "^feat", group = "🚀 Features"},
	{ message = "^fix", group = "🐛 Bug Fixes"},
	{ message = "^docs", group = "📝 Documentation"},
	{ message = "^perf", group = "🏃 Performance"},
	{ message = "^refactor", group = "🏠 Refactor"},
	{ message = "^typings", group = "⌨️ Typings"},
	{ message = "^types", group = "⌨️ Typings"},
	{ message = ".*deprecated", body = ".*deprecated", group = "🚨 Deprecation"},
	{ message = "^revert", skip = true},
	{ message = "^style", group = "🪞 Styling"},
	{ message = "^test", group = "🧪 Testing"},
	{ message = "^chore", skip = true},
	{ message = "^ci", skip = true},
	{ message = "^build", skip = true},
	{ body = ".*security", group = "🛡️ Security"},
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"