import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { twMerge } from 'tailwind-merge';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = cookies().get('NEXT_LOCALE');

  return (
    <html lang={locale?.value ?? 'es'}>
      <body className={twMerge('theme-dark', inter.className)}>{children}</body>
    </html>
  );
}
